KNOWLEDGE_BASE = [
    {"id": "kb1", "category": "services", "title": "Company Overview",
     "content": "DigitalSofts is a full-service software company founded in 2015, specializing in AI solutions, cloud services, ERP systems, and custom software development for startups and enterprises worldwide."},
    {"id": "kb2", "category": "services", "title": "Core Services",
     "content": "DigitalSofts offers AI/ML solutions, cloud infrastructure and migration, ERP implementation and customization, custom software development, mobile app development, and IT consulting."},
    {"id": "kb3", "category": "ai", "title": "AI Solutions Overview",
     "content": "DigitalSofts builds custom AI solutions including chatbots, recommendation engines, predictive analytics, computer vision systems, and generative AI applications using frameworks like LangChain, TensorFlow, and PyTorch."},
    {"id": "kb4", "category": "ai", "title": "AI Chatbot Development",
     "content": "Our AI chatbot solutions integrate with existing systems, support multi-turn conversations, and can be deployed on web, WhatsApp, or Slack, typically delivered within 6-12 weeks."},
    {"id": "kb5", "category": "ai", "title": "Predictive Analytics",
     "content": "DigitalSofts' predictive analytics services help businesses forecast demand, detect fraud, and optimize operations using machine learning models trained on historical business data."},
    {"id": "kb6", "category": "cloud", "title": "Cloud Services Overview",
     "content": "DigitalSofts provides cloud migration, architecture design, and managed services on AWS, Azure, and Google Cloud Platform, including containerization with Docker and Kubernetes."},
    {"id": "kb7", "category": "cloud", "title": "Cloud Migration Process",
     "content": "Our cloud migration process includes assessment, planning, phased migration, and post-migration optimization, typically completed in 4-12 weeks depending on system complexity."},
    {"id": "kb8", "category": "cloud", "title": "Cloud Security",
     "content": "DigitalSofts implements industry-standard security practices including encryption at rest and in transit, IAM policies, and continuous monitoring for all cloud deployments."},
    {"id": "kb9", "category": "erp", "title": "ERP Solutions Overview",
     "content": "DigitalSofts implements and customizes ERP systems including SAP, Odoo, and custom-built ERP platforms covering finance, inventory, HR, and supply chain management modules."},
    {"id": "kb10", "category": "erp", "title": "ERP Implementation Timeline",
     "content": "A typical ERP implementation with DigitalSofts takes 12-26 weeks depending on the number of modules, data migration complexity, and customization requirements."},
    {"id": "kb11", "category": "erp", "title": "ERP Support",
     "content": "DigitalSofts provides ongoing ERP support including bug fixes, module upgrades, user training, and 24/7 monitoring as part of our maintenance packages."},
    {"id": "kb12", "category": "software_development", "title": "Custom Software Development",
     "content": "DigitalSofts builds custom web and desktop applications using Python, Java, Node.js, and .NET, following agile methodology with two-week sprint cycles."},
    {"id": "kb13", "category": "software_development", "title": "Mobile App Development",
     "content": "We develop native and cross-platform mobile apps using Flutter, React Native, Swift, and Kotlin, with typical delivery timelines of 8-16 weeks."},
    {"id": "kb14", "category": "software_development", "title": "Web Development",
     "content": "DigitalSofts builds responsive, scalable web applications using React, Angular, Vue, and backend frameworks like Django, FastAPI, and Express, typically delivered in 4-10 weeks."},
    {"id": "kb15", "category": "software_development", "title": "Quality Assurance",
     "content": "All DigitalSofts projects include automated testing, code review, and QA cycles before deployment to ensure production-ready, reliable software."},
    {"id": "kb16", "category": "pricing", "title": "Pricing Model",
     "content": "DigitalSofts offers fixed-price, time-and-materials, and dedicated team pricing models. Fixed-price projects start at $5,000 for small web apps and scale up to $60,000+ for enterprise ERP systems."},
    {"id": "kb17", "category": "pricing", "title": "AI Project Pricing",
     "content": "AI solution projects typically range from $10,000 to $40,000 depending on model complexity, data volume, and integration requirements."},
    {"id": "kb18", "category": "pricing", "title": "Support Packages",
     "content": "DigitalSofts offers monthly support retainers starting at $500/month for bug fixes and minor updates, and $2,000/month for dedicated support engineers."},
    {"id": "kb19", "category": "faq", "title": "FAQ: Project Kickoff",
     "content": "Projects typically kick off within 1-2 weeks of contract signing, starting with a discovery workshop to gather requirements and define milestones."},
    {"id": "kb20", "category": "faq", "title": "FAQ: Post-Launch Support",
     "content": "Yes, DigitalSofts provides 30 days of free post-launch support for all projects, with extended support available through maintenance packages."},
    {"id": "kb21", "category": "faq", "title": "FAQ: Data Security",
     "content": "DigitalSofts follows GDPR and SOC 2 aligned practices, uses encrypted data storage, and signs NDAs with all clients to protect confidential information."},
    {"id": "kb22", "category": "faq", "title": "FAQ: Payment Terms",
     "content": "DigitalSofts typically requires a 30% upfront deposit, with remaining payments tied to project milestones or monthly billing for time-and-materials engagements."},
    {"id": "kb23", "category": "faq", "title": "FAQ: Team Composition",
     "content": "Each project is staffed with a dedicated project manager, developers, QA engineers, and a technical architect, scaled according to project size."},
    {"id": "kb24", "category": "faq", "title": "FAQ: Communication",
     "content": "DigitalSofts provides weekly progress reports and uses Slack, Jira, and video calls for continuous client communication throughout the project lifecycle."},
]
